#define COMSIG_GLOB_INTEL_DISK_PRINTED "!intel_disk_printed"
#define COMSIG_GLOB_INTEL_COMPUTER_ACTIVATED "!intel_computer_activated"
#define COMSIG_DISK_EXPIRY "intel_disk_expiring"
#define COMSIG_GLOB_TADPOLE_LANDED_IN_LZ "!tadpole_landed_in_lz"
#define COMSIG_GLOB_SHUTTLE_LANDED "!shuttle_landed"
