#define SEX_ACTION(sex_action_type) GLOB.sex_actions[sex_action_type]

#define MAX_LARVA_PREGNANCIES GLOB.max_larva_count_per_mob
#define MAX_LARVA_PREGNANCIES_SOL 3

#define MAX_AROUSAL 250
#define PASSIVE_EJAC_THRESHOLD 248
#define ACTIVE_EJAC_THRESHOLD 248
#define AROUSAL_HARD_ON_THRESHOLD 20
#define AROUSAL_TIME_TO_UNHORNY (5 SECONDS)
#define SPENT_AROUSAL_RATE (3 / (1 SECONDS))
#define IMPOTENT_AROUSAL_LOSS_RATE (3 / (1 SECONDS))


#define AROUSAL_HIGH_UNHORNY_RATE (1.5 / (1 SECONDS))
#define AROUSAL_MID_UNHORNY_RATE (0.4 / (1 SECONDS))
#define AROUSAL_LOW_UNHORNY_RATE (0.2 / (1 SECONDS))

#define MOAN_COOLDOWN 6 SECONDS
#define PAIN_COOLDOWN 6 SECONDS

#define SEX_SPEED_LOW 1
#define SEX_SPEED_MID 2
#define SEX_SPEED_HIGH 3
#define SEX_SPEED_EXTREME 4

#define SEX_SPEED_MIN 1
#define SEX_SPEED_MAX 4

#define SEX_FORCE_LOW 1
#define SEX_FORCE_MID 2
#define SEX_FORCE_HIGH 3
#define SEX_FORCE_EXTREME 4

#define SEX_FORCE_MIN 1
#define SEX_FORCE_MAX 4

#define SEX_DRAIN_STYLE_HEAL_TARGET 1
#define SEX_DRAIN_STYLE_DRAIN_STAMINA 2
#define SEX_DRAIN_STYLE_DRAIN_BLOOD_FAST 3
#define SEX_DRAIN_STYLE_DRAIN_BLOOD_SLOW 4

#define SEX_DRAIN_MIN 1
#define SEX_DRAIN_MAX 4

#define SEX_MANUAL_AROUSAL_DEFAULT 1
#define SEX_MANUAL_AROUSAL_UNAROUSED 2
#define SEX_MANUAL_AROUSAL_PARTIAL 3
#define SEX_MANUAL_AROUSAL_FULL 4

#define SEX_MANUAL_AROUSAL_MIN 1
#define SEX_MANUAL_AROUSAL_MAX 4

#define LOINHURT_GAIN_THRESHOLD 25
#define LOINHURT_LOSE_THRESHOLD 20

#define PAIN_MILD_EFFECT 10
#define PAIN_MED_EFFECT 20
#define PAIN_HIGH_EFFECT 30
#define PAIN_MINIMUM_FOR_DAMAGE PAIN_MED_EFFECT
#define PAIN_DAMAGE_DIVISOR 50

#define SEXPREF_ROUGH_SEX (1 << 0)
#define SEXPREF_CHOKING (1 << 1)
#define SEXPREF_STAMINA_DRAIN (1 << 2)
#define SEXPREF_BLOOD_DRAIN (1 << 3)
#define SEXPREF_QUICK_SEX (1 << 4)
#define SEXPREF_QUICK_SEX_HEAL (1 << 5)
#define SEXPREF_FACEHUGGER_LEWD (1 << 6)
#define SEXPREF_BURSTSCREAMS (1 << 7)
#define SEXPREF_APHRO (1 << 8)
#define SEXPREF_TENTACLE_NEST (1 << 9)
#define SEXPREF_ALL ((1 << 10) - 1)

#define VIOLATED_ALLOWED_TIME (10 MINUTES)

///hole defines
#define HOLE_MOUTH "mouth"
#define HOLE_ASS "ass"
#define HOLE_VAGINA "pussy"
#define HOLE_NIPPLE "nipple"
#define HOLE_EAR "ear"
#define HOLE_EYE "eye"
#define HOLE_BELLY "belly"

#define HOLE_LIST list(HOLE_MOUTH,HOLE_ASS,HOLE_VAGINA,HOLE_NIPPLE,HOLE_EAR,HOLE_EYE,HOLE_BELLY)
