/obj/item/storage/box/crate/loot/autosniper_lethal_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/rifle/standard_autosniper(src)
	new /obj/item/storage/backpack/marine/satchel/scout_cloak/sniper(src)
	new /obj/item/clothing/glasses/night/m42_night_goggles(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/fulton_extraction_pack/adminbus/advanced(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/rifle/autosniper(src)
	new /obj/item/ammo_magazine/packet/autosniper(src)
	new /obj/item/ammo_magazine/packet/autosniper(src)
	new /obj/item/ammo_magazine/packet/autosniper(src)
	new /obj/item/ammo_magazine/packet/autosniper(src)
	new /obj/item/attachable/motiondetector/advanced/covert(src)

/obj/item/storage/box/crate/loot/moonbeam_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/rifle/chambered/nonlethal(src) //attachments given seperately for tacticool points
	new /obj/item/attachable/scope/nightvision (src)
	new /obj/item/attachable/suppressor (src)
	new /obj/item/attachable/stock/tl127stock/moonbeam(src)
	new /obj/item/storage/backpack/marine/satchel/scout_cloak/sniper(src)
	new /obj/item/clothing/glasses/night/m42_night_goggles(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/storage/box/zipcuffs(src)
	new /obj/item/fulton_extraction_pack/adminbus/advanced(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/tranq(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/bluescreen(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/bluescreen(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/bluescreen(src)
	new /obj/item/ammo_magazine/rifle/chamberedrifle/bluescreen(src)
	new /obj/item/ammo_magazine/packet/p86x70mm/tranq(src)
	new /obj/item/attachable/motiondetector/advanced/covert(src)

/obj/item/storage/box/crate/loot/smartpistol_spec/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)
	new /obj/item/ammo_magazine/pistol/standard_pistol/smart_pistol(src)

/obj/item/storage/box/crate/loot/infiltration_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/clothing/glasses/night/m42_night_goggles(src)
	new /obj/item/clothing/gloves/marine/insulated(src)
	new /obj/item/storage/backpack/marine/satchel/scout_cloak(src)
	if(SSmapping.configs[GROUND_MAP].environment_traits[MAP_COLD])
		new /obj/item/bodybag/tarp/snow(src)
	else
		new /obj/item/bodybag/tarp(src)
	new /obj/item/storage/box/stuns(src)
	new /obj/item/storage/holster/belt/pistol/g22/tranq(src)
	new /obj/item/storage/box/zipcuffs(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/ammo_magazine/pistol/g22tranq(src)
	new /obj/item/assembly/signaler (src)
	new /obj/item/detpack(src)
	new /obj/item/fulton_extraction_pack/adminbus/advanced(src)
	new /obj/item/explosive/plastique(src)
	new /obj/item/reagent_containers/hypospray/autoinjector/sleeptoxin(src)
	new /obj/item/reagent_containers/hypospray/autoinjector/sleeptoxin(src)
	new /obj/item/reagent_containers/hypospray/autoinjector/sleeptoxin(src)
	new /obj/item/roller/medevac(src)
	new /obj/item/medevac_beacon(src)
	new /obj/item/clothing/under/marine/sneaking(src)
	new /obj/item/attachable/motiondetector/advanced/pocket/covert(src)

/obj/item/storage/box/crate/loot/infiltration_lethal_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/storage/holster/belt/pistol/m4a3/specops(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/ammo_magazine/pistol/m1911/ap(src)
	new /obj/item/clothing/glasses/night/m42_night_goggles(src)
	new /obj/item/clothing/gloves/marine/insulated(src)
	new /obj/item/storage/backpack/marine/satchel/scout_cloak(src)
	if(SSmapping.configs[GROUND_MAP].environment_traits[MAP_COLD])
		new /obj/item/bodybag/tarp/snow(src)
	else
		new /obj/item/bodybag/tarp(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/assembly/signaler (src)
	new /obj/item/detpack(src)
	new /obj/item/detpack(src)
	new /obj/item/detpack(src)
	new /obj/item/detpack(src)
	new /obj/item/fulton_extraction_pack/adminbus/advanced(src)
	new /obj/item/explosive/plastique(src)
	new /obj/item/explosive/plastique(src)
	new /obj/item/explosive/plastique(src)
	new /obj/item/explosive/plastique(src)
	new /obj/item/reagent_containers/hypospray/autoinjector/polyacid(src)
	new /obj/item/reagent_containers/hypospray/autoinjector/polyacid(src)
	new /obj/item/reagent_containers/hypospray/autoinjector/polyacid(src)
	new /obj/item/clothing/under/marine/sneaking(src)
	new /obj/item/attachable/motiondetector/advanced/pocket/covert(src)

/obj/item/storage/box/crate/loot/gheist_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/pamphlet/rifleman(src)
	new /obj/item/weapon/gun/rifle/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon/pox(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon/pox(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon/pox(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon/pox(src)
	new /obj/item/ammo_magazine/rifle/boltclip/dragoon/pox(src)
	new /obj/item/clothing/glasses/night/m42_night_goggles(src)
	new /obj/item/skillsoft/lightfooted(src)
	new /obj/item/fulton_extraction_pack/adminbus/advanced(src)
	new /obj/item/assembly/signaler (src)
	new /obj/item/detpack(src)
	new /obj/item/detpack(src)
	new /obj/item/detpack(src)
	new /obj/item/detpack(src)

/obj/item/storage/box/crate/loot/targetrifle_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/rifle/standard_smarttargetrifle(src)
	new /obj/item/clothing/glasses/night/m56_goggles(src)
	new /obj/item/fulton_extraction_pack/adminbus/advanced(src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_smarttargetrifle (src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle/highimpact(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle/heavyrubber(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle/tungsten(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle/flak(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle/plasmaloss(src)
	new /obj/item/ammo_magazine/rifle/standard_spottingrifle/incendiary(src)

/obj/item/storage/box/crate/loot/thermobaric_pack
	icon_state = "rocket_case"

/obj/item/storage/box/crate/loot/thermobaric_pack/PopulateContents()
	. = ..()
	new /obj/item/weapon/gun/launcher/rocket/m57a4/t57(src)
	new /obj/item/weapon/gun/launcher/rocket/m57a4/t57(src)
	new /obj/item/weapon/gun/launcher/rocket/m57a4/t57(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src) // three launchers and 10 arrays. Common. 200.

/obj/item/storage/box/crate/loot/thermobaric_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/launcher/rocket/m57a4/t57(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src)
	new /obj/item/ammo_magazine/rocket/m57a4(src) // three launchers and 10 arrays. Common. 200.

/obj/item/storage/box/crate/loot/tesla_pack/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/energy/lasgun/lasrifle/tesla(src)
	new /obj/item/weapon/gun/energy/lasgun/lasrifle/tesla(src)
	new /obj/item/weapon/gun/energy/lasgun/lasrifle/tesla(src) // 180 and nothing else. Have fun.

/obj/item/storage/box/crate/loot/tx54_pack/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/rifle/tx54(src)
	new /obj/item/weapon/gun/rifle/tx54(src)
	new /obj/item/weapon/gun/rifle/tx54(src)
	new /obj/item/ammo_magazine/rifle/tx54(src)
	new /obj/item/ammo_magazine/rifle/tx54(src)
	new /obj/item/ammo_magazine/rifle/tx54(src)
	new /obj/item/ammo_magazine/rifle/tx54(src)
	new /obj/item/ammo_magazine/rifle/tx54/he(src)
	new /obj/item/ammo_magazine/rifle/tx54/he(src)
	new /obj/item/ammo_magazine/rifle/tx54/he(src)
	new /obj/item/ammo_magazine/rifle/tx54/he(src)

// Uncommon

/obj/item/storage/box/crate/loot/materials_pack/Initialize(mapload)
	. = ..()
	new /obj/item/stack/sheet/plasteel/large_stack(src)
	new /obj/item/stack/sheet/plasteel/large_stack(src)
	new /obj/item/stack/sheet/metal/large_stack(src)
	new /obj/item/stack/sheet/metal/large_stack(src)
	new /obj/item/stack/sheet/metal/large_stack(src)
	new /obj/item/stack/sheet/metal/large_stack(src)
	new /obj/item/stack/sandbags_empty/full(src)
	new /obj/item/stack/sandbags_empty/full(src)
	new /obj/item/stack/sandbags_empty/full(src)
	new /obj/item/stack/sandbags_empty/full(src)
	new /obj/item/tool/shovel/etool(src)
	new /obj/item/tool/shovel/etool(src)
	new /obj/item/tool/shovel/etool(src)
	new /obj/item/tool/shovel/etool(src)

/obj/item/storage/box/crate/loot/recoilless_pack
	icon_state = "rocket_case"

/obj/item/storage/box/crate/loot/recoilless_pack/PopulateContents()
	. = ..()
	new /obj/item/storage/holster/backholster/rpg/full(src)
	new /obj/item/storage/holster/backholster/rpg/full(src)
	new /obj/item/storage/holster/backholster/rpg/full(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)

/obj/item/storage/box/crate/loot/recoilless_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/storage/holster/backholster/rpg/full(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heat(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/light(src)
	new /obj/item/ammo_magazine/rocket/recoilless/low_impact(src)
	new /obj/item/ammo_magazine/rocket/recoilless/low_impact(src)
	new /obj/item/ammo_magazine/rocket/recoilless/low_impact(src)
	new /obj/item/ammo_magazine/rocket/recoilless/low_impact(src)
	new /obj/item/ammo_magazine/rocket/recoilless/low_impact(src)
	new /obj/item/ammo_magazine/rocket/recoilless/low_impact(src)
	new /obj/item/ammo_magazine/rocket/recoilless/smoke(src)
	new /obj/item/ammo_magazine/rocket/recoilless/smoke(src)
	new /obj/item/ammo_magazine/rocket/recoilless/smoke(src)
	new /obj/item/ammo_magazine/rocket/recoilless/smoke(src)
	new /obj/item/ammo_magazine/rocket/recoilless/smoke(src)
	new /obj/item/ammo_magazine/rocket/recoilless/smoke(src)
	new /obj/item/ammo_magazine/rocket/recoilless/cloak(src)
	new /obj/item/ammo_magazine/rocket/recoilless/cloak(src)
	new /obj/item/ammo_magazine/rocket/recoilless/cloak(src)
	new /obj/item/ammo_magazine/rocket/recoilless/cloak(src)
	new /obj/item/ammo_magazine/rocket/recoilless/cloak(src)
	new /obj/item/ammo_magazine/rocket/recoilless/cloak(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heam(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heam(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heam(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heam(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heam(src)
	new /obj/item/ammo_magazine/rocket/recoilless/heam(src)


/obj/item/storage/box/crate/loot/railgun_pack/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/rifle/railgun(src)
	new /obj/item/weapon/gun/rifle/railgun(src)
	new /obj/item/weapon/gun/rifle/railgun(src)
	new /obj/item/ammo_magazine/railgun/smart(src)
	new /obj/item/ammo_magazine/railgun/smart(src)
	new /obj/item/ammo_magazine/railgun/smart(src)
	new /obj/item/ammo_magazine/railgun/smart(src)
	new /obj/item/ammo_magazine/railgun/hvap(src)
	new /obj/item/ammo_magazine/railgun/hvap(src)
	new /obj/item/ammo_magazine/railgun/hvap(src)
	new /obj/item/ammo_magazine/railgun/hvap(src)
	new /obj/item/ammo_magazine/railgun(src)
	new /obj/item/ammo_magazine/railgun(src)
	new /obj/item/ammo_magazine/railgun(src)
	new /obj/item/ammo_magazine/railgun(src)

/obj/item/storage/box/crate/loot/scoutrifle_pack
	icon_state = "sniper_case"

/obj/item/storage/box/crate/loot/scoutrifle_pack/PopulateContents()
	. = ..()
	new /obj/item/weapon/gun/rifle/tx8(src)
	new /obj/item/weapon/gun/rifle/tx8(src)
	new /obj/item/weapon/gun/rifle/tx8(src)
	new /obj/item/ammo_magazine/packet/scout_rifle(src)
	new /obj/item/ammo_magazine/packet/scout_rifle(src)
	new /obj/item/ammo_magazine/packet/scout_rifle(src)
	new /obj/item/ammo_magazine/packet/scout_rifle(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)

/obj/item/storage/box/crate/loot/scoutrifle_pack_spec/Initialize(mapload)
	. = ..()
	new /obj/item/weapon/gun/rifle/tx8(src)
	new /obj/item/ammo_magazine/packet/scout_rifle(src)
	new /obj/item/storage/belt/marine/tx8(src)
	new /obj/item/storage/pouch/magazine/large/tx8full(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8(src)
	new /obj/item/ammo_magazine/rifle/tx8/incendiary(src)
	new /obj/item/ammo_magazine/rifle/tx8/incendiary(src)
	new /obj/item/ammo_magazine/rifle/tx8/incendiary(src)
	new /obj/item/ammo_magazine/rifle/tx8/incendiary(src)
	new /obj/item/ammo_magazine/rifle/tx8/incendiary(src)
	new /obj/item/ammo_magazine/rifle/tx8/incendiary(src)
	new /obj/item/ammo_magazine/rifle/tx8/impact(src)
	new /obj/item/ammo_magazine/rifle/tx8/impact(src)
	new /obj/item/ammo_magazine/rifle/tx8/impact(src)
	new /obj/item/ammo_magazine/rifle/tx8/impact(src)
	new /obj/item/ammo_magazine/rifle/tx8/impact(src)
	new /obj/item/ammo_magazine/rifle/tx8/impact(src)
	new /obj/item/clothing/glasses/night/m42_night_goggles(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/storage/box/explosive_mines(src)
	new /obj/item/attachable/motiondetector/advanced/covert(src)
